name: Concurrency Workflow 

on: [workflow_dispatch]

jobs:
    first_job:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4 # using checkout action from Marketplace

            - name: List repo files
              run: ls -ltra

            - name: Granting permissions to script
              run: sudo chmod +x ascii-gen.sh

            - name: Executing Shell script
              run: ./ascii-gen.sh
    deploy:
        needs: first_job
        runs-on: ubuntu-latest
        concurrency:
            group: dev-concurrency-test # Let's if we trigger a job manually and then trigger another job after 2-3 sec, it will be in pending state, but if trigger the third job again after 2-3s since the second job was in pending it will get cancelled with message like "Canceling since a higher priority waiting request for 'dev-concurrency-test' exists"
            cancel-in-progress: false # with 'true' flag it will cancel any currently running job or workflow in the same concurrency group,but with 'false' flag, it will not cancel the already running job, instead it will wait for a job to complete.
        steps: 
            - name: run docker
              run: |
                docker run -d hello-world
                sleep 420

              
