name: Testing event workflows and activities

on: 
  workflow_dispatch:
  push:
    branches:
        - main
        - '!feature/*'
  pull_request: 
    types: 
        - opened
        - closed
    paths-ignore: 
        - README.md
    branches: 
        - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - name: run a command
              run: echo this workflow/job/step is executed for event type - ${{ github.event_name }}
              
