name: Generate Ascii Art

on: push

jobs:
    first_job:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4 # using checkout action from Marketplace
            - name: Print message, List and Read files
              run: |
                   echo "This is the first workflow"
                   ls -lart
                   cat README.md
            - name: Install cowsay binary
              run: sudo apt-get install -y cowsay       

            - name: Generate ASCII
              run: cowsay -f dog 'Woof woof! I can bite... :p' >> generate_ascii.txt
              
            - name: Print ascii file
              run: cat generate_ascii.txt 

            - name: List all repo files in the runner
              run: ls -lart  
