name: timeout test

on: [workflow_dispatch, push]

jobs:
    first_job:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4 # using checkout action from Marketplace

            - name: List repo files
              run: ls -ltra

            - name: Granting permissions to script
              run: sudo chmod +x ascii-gen.sh

            - name: Executing Shell script
              run: ./ascii-gen.sh

            - name: Testing github actions timeout
              timeout-minutes: 1 # this what we are testing in this workflow
              run: sleep 60000   
              
